#!/bin/sh
set -eu

# Source helper functions.
. ./bin/helpers

install_deps jq unzip

# Install LXD
install_lxd

# Install go from Snap.
if ! command -v go > /dev/null; then
    snap install go --channel=latest/stable --classic
fi

# Install latest lxd-migrate binary tool.
go install github.com/canonical/lxd/lxd-migrate@latest

# Configure LXD
lxd init --auto
lxc config set core.https_address :8443

checkIPAddresses() {
    instName=$1

    address=$(lxc query "/1.0/instances/${instName}/state" | jq -r ".network.eth0.addresses | .[] | select(.scope | contains(\"global\")) | .address" 2>/dev/null || true)
    if [ -z "${address}" ]; then
        address=$(lxc query "/1.0/instances/${instName}/state" | jq -r ".network.enp5s0.addresses | .[] | select(.scope | contains(\"global\")) | .address" 2>/dev/null || true)
    fi

    if [ -z "${address}" ]; then
        echo "===> FAIL: No network interface: ${instName}"

        # Show the network state.
        echo "===> DEBUG: network state: ${instName}"
        lxc info "${instName}"
        return 1
    fi

    FAIL=0

    # IPv4 address
    if echo "${address}" | grep "\." -q; then
        echo "===> PASS: IPv4 address: ${instName}"
    else
        echo "===> FAIL: IPv4 address: ${instName}"
        FAIL=1
    fi

    # IPv6 address
    if echo "${address}" | grep ":" -q; then
        echo "===> PASS: IPv6 address: ${instName}"
    else
        echo "===> FAIL: IPv6 address: ${instName}"
        FAIL=1
    fi

    return "${FAIL}"
}

checkDNS() {
    instName=$1

    # Test lxd-agent and DNS resolution.
    if lxc exec "${instName}" -- nslookup canonical.com >/dev/null 2>&1; then
        echo "===> PASS: DNS resolution: ${instName}"
        return 0
    fi

    if lxc exec "${instName}" -- getent hosts canonical.com >/dev/null 2>&1; then
        echo "===> PASS: DNS resolution: ${instName}"
        return 0
    fi

    echo "===> FAIL: DNS resolution: ${instName}"
    return 1
}

# conversion_vm creates a new LXD virtual machine from the image on the given path.
# A dedicated storage pool of the given type will be created for a new virtual machine.
#
# Input arguments:
# 1: Name of new virtual machine.
# 2: Type of the storage pool.
# 3: Path to the image.
conversion_vm() {
    conversion vm "$1" "$2" "$3"
}

# conversion_container creates a new LXD container from the filesystem of the existing container.
#
# Input arguments:
# 1: Name of the existing container.
conversion_container() {
    conversion container "$1" "" "/"
}

# conversion runs lxd-migrate for the given image path. For virtual machine, lxd-migrate is
# executed on the localhost. For container, lxd-migrate will be installed and executed from
# an existing container.
conversion() {
    instType=$1
    instName=$2
    poolType=$3
    imgPath=$4

    if [ "${instType}" == "vm" ]; then
        echo "==> TEST: Conversion: Import virtual-machine '${instName}' on '${poolType}' storage pool"

        poolName="conversion-${poolType}"
        hostAddr="127.0.0.1"
        instTypeCode="2" # VM in migration questioneer.

        lxdMigrateCmd="sudo lxd-migrate --conversion format"

        # Ensure instance and storage pool with the given name do not exist.
        lxc delete -f "${instName}" 2>/dev/null || true
        lxc storage delete "${poolName}" 2>/dev/null || true

        # Create storage pool.
        lxc storage create "${poolName}" "${poolType}"

    elif [ "${instType}" == "container" ]; then
        echo "==> TEST: Conversion: Import container '${instName}'"

        poolName=""
        hostAddr=$(lxc network show lxdbr0 | awk '/ipv4.address:/ {split($2, arr, "/"); print arr[1]}')
        instTypeCode="1" # Container.

        lxdMigrateCmd="lxc exec ${instName} -- /root/go/bin/lxd-migrate" # --conversion=

        # Install rsync and lxd-migrate.
        lxc exec "${instName}" -- apt update
        lxc exec "${instName}" -- apt install rsync
        lxc exec "${instName}" -- snap install go --channel=latest/stable --classic
        lxc exec "${instName}" -- go install github.com/canonical/lxd/lxd-migrate@latest
        lxc exec "${instName}" -- /root/go/bin/lxd-migrate --version

        # Set instName to the name of the new container that will be created
        # from the existing one.
        instName="${instName}-migration"
    else
        echo "Invalid instance type '${instType}'. Valid types are 'container' and 'vm'."
        return 1
    fi

    # Generate trust token for conversion.
    token=$(lxc config trust add --name migrate | awk 'NR==2') || exit 1
    if [ ! "${token}" ]; then
        echo "Failed to generate LXD trust token!"
        exit 1
    fi

    # Migration questions.
    {
        echo "${hostAddr}"     # Address of the target LXD server.
        sleep 1
        echo "y"               # Yes, this is correct fingerprint.
        sleep 1
        echo "1"               # Use a certificate token.
        echo "${token}"        # Token.
        echo "${instTypeCode}" # Instace type (1 == container, 2 == virtual-machine).
        echo "${instName}"     # Instance name.
        echo "${imgPath}"      # Local image path (or filesystem path in case of container).
        echo "no"              # Enable UEFI.

        # Configure storage pool.
        if [ "${poolName}" != "" ]; then
            echo "4"           # Change storage pool settings.
            echo "${poolName}" # Pool name.
            echo "yes"         # Configure pool size?
            echo "10GiB"       # Pool size.
        fi

        # Begin the migration with the above configuration
        sleep 1
        echo "1"
    } | $lxdMigrateCmd

    # Start the instance.
    echo "Starting instance ${instName}..."
    lxc start "${instName}"

    # Wait for the instance to be ready and ensure it has global ip address.
    echo "Waiting instance ${instName} to start..."
    waitInstanceReady "${instName}"
    sleep 15

    echo "Check network connectivity of instance ${instName}..."
    checkIPAddresses "${instName}"

    echo "Check DNS resolution of instance ${instName}..."
    checkDNS "${instName}"

    echo "Stopping instance ${instName}..."
    lxc stop "${instName}" --timeout=30

    # Cleanup.
    lxc delete -f "${instName}"

    if [ "${poolName}" != "" ]; then
        lxc storage delete "${poolName}"
    fi
}

# Test container migration using conversion mode.
lxc launch ubuntu-minimal:22.04 c1
conversion_container "c1"
lxc delete -f c1

# Test QCOW2 images.
IMAGE_PATH="/tmp/qcow2"

lxc image export images:alpine/edge "${IMAGE_PATH}" --vm
conversion_vm vm-alpine-qcow2-lvm lvm "${IMAGE_PATH}.root"

lxc image export images:centos/9-Stream "${IMAGE_PATH}" --vm
conversion_vm vm-centos9-qcow2-btrfs btrfs "${IMAGE_PATH}.root"

# Test VMDK image.
IMAGE_PATH="/tmp/ubuntu-24.04.vmdk"
if [ ! -f "${IMAGE_PATH}" ]; then
    wget https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.vmdk -O "${IMAGE_PATH}"
fi

conversion_vm vm-u24-vmdk-dir dir "${IMAGE_PATH}"
conversion_vm vm-u24-vmdk-zfs zfs "${IMAGE_PATH}"

# Use custom volume for backups. Images for conversion will be uploaded here.
lxc storage create backups-pool zfs
lxc storage volume create backups-pool backups-vol
lxc config set storage.backups_volume=backups-pool/backups-vol

conversion_vm vm-u24-vmdk-dir-bupvol dir "${IMAGE_PATH}"
conversion_vm vm-u24-vmdk-zfs-bupvol zfs "${IMAGE_PATH}"

# Cleanup.
lxc config unset storage.backups_volume
lxc storage volume delete backups-pool backups-vol
lxc storage delete backups-pool

# shellcheck disable=SC2034
FAIL=0
