#!/bin/bash
set -eux

# Install dependencies
install_deps jq

# Install LXD
install_lxd

# Configure LXD
lxc network create lxdbr0
lxc profile device add default eth0 nic network=lxdbr0

poolName="ctpool$$"
poolDriver=dir

echo "==> Create storage pool using driver ${poolDriver}"
lxc storage create "${poolName}" "${poolDriver}"

echo "==> Create container and boot"
# XXX: not using ubuntu-minimal-daily:24.04 due to unreliability
lxc launch "${TEST_IMG:-ubuntu:24.04}" c1 -s "${poolName}" -c security.nesting=true
lxc info c1

echo "==> Checking devlxd is working"

# devlxd is enabled by default and should work
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0 | jq
if hasNeededAPIExtension cloud_init; then
  lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/devices | jq
fi
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/config | jq
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -q 'instance-id:'
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -q 'local-hostname:'

# Restart the container
lxc restart -f c1

# devlxd should be running after restart
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0 | jq
if hasNeededAPIExtension cloud_init; then
  lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/devices | jq
fi
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/config | jq
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -q 'instance-id:'
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -q 'local-hostname:'

# Disable devlxd
lxc config set c1 security.devlxd false

echo "==> Checking devlxd is not working"

! lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0 || false

lxc restart -f c1

# devlxd should not be running after restart
! lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0 || false

echo "==> Checking devlxd can be enabled live"

# Enable devlxd
lxc config set c1 security.devlxd true
lxc config set c1 security.devlxd.images true

# devlxd should be running after the config is enabled
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0 | jq
if hasNeededAPIExtension cloud_init; then
  lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/devices | jq
fi
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/config | jq
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -q 'instance-id:'
lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock http://custom.socket/1.0/meta-data | grep -q 'local-hostname:'

if hasNeededAPIExtension instance_ready_state; then
  # test instance Ready state
  lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock -X PATCH -d '{"state":"Ready"}' http://custom.socket/1.0
  [ "$(lxc config get c1 volatile.last_state.ready)" = "true" ]

  lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock -X PATCH -d '{"state":"Started"}' http://custom.socket/1.0
  [ "$(lxc config get c1 volatile.last_state.ready)" = "false" ]

  lxc exec c1 -- curl -s --unix-socket /dev/lxd/sock -X PATCH -d '{"state":"Ready"}' http://custom.socket/1.0
  [ "$(lxc config get c1 volatile.last_state.ready)" = "true" ]
  lxc stop -f c1
  sleep 5
  [ "$(lxc config get c1 volatile.last_state.ready)" = "false" ]

  lxc start c1
  waitInstanceBooted c1
else
  echo "Skipping instance Ready state tests, not supported"
fi

# Below tests for image export rely on an event being emitted on export. This will not be backported to 4.0 or 5.0,
# so exit the test here.
if echo "${LXD_SNAP_CHANNEL}" | grep -E '^([45]\.0)/'; then
  echo "Skipping devlxd image export tests, not supported"
  FAIL=0
  exit
fi

lxc exec c1 -- mkdir -p /etc/systemd/system/snapd.service.d
lxc file push - c1/etc/systemd/system/snapd.service.d/override.conf << EOF
# Workaround for https://bugs.launchpad.net/snapd/+bug/2104066
[Service]
Environment=SNAPD_STANDBY_WAIT=1m
EOF
lxc exec c1 -- systemctl daemon-reload
lxc exec c1 -- systemctl restart snapd.service

# We need snapd to be ready before the next tests. Finagle the waitSnapdSeed function definition into the container and run it.
# shellcheck disable=SC3044 # Ignore "declare is undefined" shellcheck error.
lxc exec c1 -- snap wait system seed.loaded
lxc exec c1 -- snap install lxd --channel="${LXD_SNAP_CHANNEL}" --cohort=+
lxc exec c1 -- /snap/bin/lxd init --auto

lxc monitor --type lifecycle --format json > monitor.json 2>&1 &
monitorPID="${!}"

# Launch an image we know is on the host.
lxc exec c1 -- /snap/bin/lxc launch "${TEST_IMG:-ubuntu:24.04}" c1c1
lxc exec c1 -- /snap/bin/lxc info c1c1 | grep -F RUNNING

kill -9 "${monitorPID}"

# If the guest retrieved the image from the host, the host should emit an "image-retrieved" lifecycle event. The
# requestor address tells us that this was definitely the guest.
# Newer LXD versions use the protocol instead of the requestor address to distinguish devlxd requests
[ "$(grep -wF 'image-retrieved' monitor.json | jq -r '.metadata.requestor.address')" = "@devlxd" ] || \
  [ "$(grep -wF 'image-retrieved' monitor.json | jq -r '.metadata.requestor.protocol')" = "devlxd" ]
rm monitor.json

echo "==> Deleting container"
lxc delete -f c1
lxc profile device remove default eth0

echo "==> Deleting storage pool"
lxc storage delete "${poolName}"

echo "==> Deleting storage pool"
lxc network delete lxdbr0

# shellcheck disable=SC2034
FAIL=0
