#!/bin/sh
set -eux

CNAME="docker-$$"

# Install LXD
install_lxd

# Create the container
lxc launch images:ubuntu/bionic "${CNAME}" -c security.nesting=true "$@"

(
cat << EOF
#!/bin/sh
# Wait for network
sleep 10
set -eux

# Install distro docker
apt-get update --yes --force-yes
apt-get install --no-install-recommends --yes --force-yes apparmor docker.io wget
systemctl start apparmor

# Stop the distro docker
systemctl stop docker.service
systemctl stop docker.socket

# Download binaries built from current git head of the Docker repo.
for BIN in docker dockerd docker-containerd docker-containerd-shim docker-init docker-proxy docker-runc; do
    wget -q "https://master.dockerproject.org/linux/x86_64/\${BIN}" -O "/usr/bin/\${BIN}" && \
        chmod +x "/usr/bin/\${BIN}"
done

# Start docker again
systemctl start docker
sleep 5

# Test whether we can pull a simple Docker image.
docker pull busybox:latest

# Test whether we can remove a simple Docker image.
docker rmi busybox:latest

# Show docker info (client and daemon version, etc.)
docker info

# Run a basic hello-world
docker run hello-world
EOF
) | lxc exec "${CNAME}" -- sh -eux

lxc delete --force "${CNAME}"

# shellcheck disable=SC2034
FAIL=0
