#!/bin/bash
set -eu

# Install LXD
install_lxd

# Configure LXD
lxc storage create default zfs
lxc profile device add default root disk path=/ pool=default
lxc network create lxdbr0
lxc profile device add default eth0 nic network=lxdbr0 name=eth0

IMAGE="${TEST_IMG:-ubuntu-daily:24.04}"

if [ "${1}" = "nvidia" ]; then
	# Enable SR-IOV
	/usr/lib/nvidia/sriov-manage -e ALL

	# Confirm GPU is online
	nvidia-smi

	# Disable MIG if enabled
	nvidia-smi -mig 0
fi

# LXD resource API
lxc info --resources

# Select VM secure boot config syntax based on server API support.
vm_secureboot_config="security.secureboot=false"
if hasNeededAPIExtension instance_boot_mode; then
	vm_secureboot_config="boot.mode=uefi-nosecureboot"
fi

# Launch test instances
for i in $(seq 1 4); do
	lxc init "${IMAGE}" "v${i}" --vm -c "${vm_secureboot_config}"
	if [ "${1}" = "nvidia" ]; then
		lxc config device add "v${i}" vgpu gpu gputype=mdev pci=0000:07:00.0 mdev=nvidia-468
	fi
	lxc start "v${i}"
done

# Wait for them to start and list
sleep 30
lxc list

if [ "${1}" = "nvidia" ]; then
	# Validate NVIDIA vGPU
	lxc exec v4 -- apt-get update
	lxc exec v4 -- apt-get install --no-install-recommends --yes build-essential wget pciutils linux-headers-virtual
	lxc exec v4 -- wget -6 http://canonical-lxd.stgraber.org/nvidia/v14.0/nvidia-guest.deb
	lxc exec v4 -- apt-get install --yes /root/nvidia-guest.deb
	lxc exec v4 -- nvidia-smi
fi

# shellcheck disable=SC2034
FAIL=0
