#!/bin/sh
set -eu

# Install LXD
install_lxd

# Configure LXD
lxc storage create default zfs
lxc profile device add default root disk path=/ pool=default
lxc network create lxdbr0
lxc profile device add default eth0 nic network=lxdbr0 name=eth0

# Confirm GPU is online
nvidia-smi

# LXD resource API
lxc info --resources

# Setup MIG
nvidia-smi -mig 1
nvidia-smi mig -lgip
nvidia-smi mig -cgi 2g.10gb,1g.5gb,1g.5gb
nvidia-smi mig -lgi
nvidia-smi mig -lcip
nvidia-smi mig -cci 1g.5gb -gi 7
nvidia-smi mig -cci 1g.5gb -gi 13
nvidia-smi mig -cci 1c.2g.10gb,1c.2g.10gb -gi 5
nvidia-smi

UUIDS="$(nvidia-smi -L | sed -n "/(UUID: MIG-/ s/.* \(MIG-[^)]\+\))$/\1/p")"
UUID1="$(echo "$UUIDS" | sed -n '1p')"
UUID2="$(echo "$UUIDS" | sed -n '2p')"
UUID3="$(echo "$UUIDS" | sed -n '3p')"
UUID4="$(echo "$UUIDS" | sed -n '4p')"

# Launch test containers
lxc init ubuntu-daily:22.04 nvidia-mig1 -c nvidia.runtime=true
lxc config device add nvidia-mig1 gpu0 gpu gputype=mig mig.uuid="$UUID1" pci=07:00.0
lxc init ubuntu-daily:22.04 nvidia-mig2 -c nvidia.runtime=true
lxc config device add nvidia-mig2 gpu0 gpu gputype=mig mig.uuid="$UUID2" pci=07:00.0
lxc init ubuntu-daily:22.04 nvidia-mig3 -c nvidia.runtime=true
lxc config device add nvidia-mig3 gpu0 gpu gputype=mig mig.uuid="$UUID3" pci=07:00.0
lxc init ubuntu-daily:22.04 nvidia-mig4 -c nvidia.runtime=true
lxc config device add nvidia-mig4 gpu0 gpu gputype=mig mig.uuid="$UUID4" pci=07:00.0
lxc start nvidia-mig1
lxc exec nvidia-mig1 -- nvidia-smi
lxc start nvidia-mig2
lxc exec nvidia-mig2 -- nvidia-smi
lxc start nvidia-mig3
lxc exec nvidia-mig3 -- nvidia-smi
lxc start nvidia-mig4
lxc exec nvidia-mig4 -- nvidia-smi

lxc stop nvidia-mig4
lxc config device add nvidia-mig4 gpu1 gpu gputype=mig mig.uuid="$UUID1" vendorid=10de productid=20f1
lxc config device add nvidia-mig4 gpu2 gpu gputype=mig mig.uuid="$UUID2" vendorid=10de productid=20f1
lxc start nvidia-mig4
lxc exec nvidia-mig4 -- nvidia-smi

# Wait for them to start and list
lxc list

# Stop all instances
lxc stop --all

# Cleanup MIG
nvidia-smi mig -dci
nvidia-smi mig -dgi
nvidia-smi -mig 0

# shellcheck disable=SC2034
FAIL=0
