#!/bin/sh
set -eu

# Install dependencies
install_deps attr

# Install LXD
install_lxd

# Configure LXD
snap set lxd shiftfs.enable=true
lxd init --auto

# Test
set -x

lxc launch ubuntu-daily:22.04 c1
sleep 10
lxc exec c1 -- apt-get update
lxc exec c1 -- apt-get install --no-install-recommends --yes attr fuse2fs

## setxattr
lxc exec c1 -- touch xattr-test
! lxc exec c1 -- setfattr -n trusted.overlay.opaque -v y xattr-test || false
lxc config set c1 security.syscalls.intercept.setxattr true
lxc restart c1 -f
lxc exec c1 -- setfattr -n trusted.overlay.opaque -v y xattr-test
[ "$(getfattr --only-values --absolute-names -n trusted.overlay.opaque /var/snap/lxd/common/lxd/containers/c1/rootfs/root/xattr-test)" = "y" ]

## mknod
! lxc exec c1 -- mknod mknod-test c 1 3 || false
lxc config set c1 security.syscalls.intercept.mknod true
lxc restart c1 -f

## Relative path
lxc exec c1 -- mknod mknod-test c 1 3

## Absolute path on tmpfs
lxc exec c1 -- mknod /dev/mknod-test c 1 3

## Absolute path on rootfs
lxc exec c1 -- mknod /root/mknod-test1 c 1 3

## bpf (needs 5.9 or higher)
if runsMinimumKernel 5.9; then
    lxc config set c1 security.syscalls.intercept.bpf=true security.syscalls.intercept.bpf.devices=true
    lxc restart c1 -f
else
    echo "Skipping security.syscalls.intercept.bpf config as the kernel is too old"
fi

if hasNeededAPIExtension container_syscall_intercept_mount; then
    ## mount
    truncate -s 10G loop.img
    LOOP=$(losetup -f --show loop.img)
    lxc config device add c1 loop unix-block source="${LOOP}" path=/dev/sda
    lxc exec c1 -- mkfs.ext4 -f /dev/sda
    ! lxc exec c1 -- mount /dev/sda /mnt || false
    lxc config set c1 security.syscalls.intercept.mount=true

    lxc config set c1 security.syscalls.intercept.mount.allowed=ext4
    lxc restart c1 -f
    lxc exec c1 -- mount /dev/sda /mnt
    [ "$(lxc exec c1 -- stat --format=%u:%g /mnt)" = "65534:65534" ]
    lxc exec c1 -- umount /mnt

    lxc config set c1 security.syscalls.intercept.mount.shift=true
    lxc exec c1 -- mount /dev/sda /mnt
    [ "$(lxc exec c1 -- stat --format=%u:%g /mnt)" = "0:0" ]
    lxc exec c1 -- umount /mnt

    if hasNeededAPIExtension container_syscall_intercept_mount_fuse; then
        lxc config unset c1 security.syscalls.intercept.mount.allowed
        lxc config set c1 security.syscalls.intercept.mount.fuse=ext4=fuse2fs
        lxc restart c1 -f

        lxc exec c1 -- mount /dev/sda /mnt
        [ "$(lxc exec c1 -- stat --format=%u:%g /mnt)" = "0:0" ]
        lxc exec c1 -- umount /mnt
    else
        echo "Skipping mount fuse tests as the container_syscall_intercept_mount_fuse API extension is missing"
    fi

    ## cleanup
    lxc delete -f c1
    losetup -d "${LOOP}"
    rm -f loop.img
else
    echo "Skipping mount tests as the container_syscall_intercept_mount API extension is missing"
fi

# shellcheck disable=SC2034
FAIL=0
