#!/bin/bash
set -eux

# Install dependencies
install_deps iputils-ping

# Install LXD
install_lxd

# Configure LXD.
lxc project switch default
lxc storage create default dir

IMAGE="${TEST_IMG:-ubuntu-daily:24.04}"

# Set global sysctl.
sysctl net.ipv6.conf.all.forwarding=1
sysctl net.ipv6.conf.all.proxy_ndp=1

# Setup dummy parent interface.
ip link add dummy0 type dummy
sysctl net.ipv6.conf.dummy0.proxy_ndp=1
sysctl net.ipv6.conf.dummy0.forwarding=1
sysctl net.ipv4.conf.dummy0.forwarding=1
sysctl net.ipv6.conf.dummy0.accept_dad=0
ip link set dummy0 up
ip addr add 192.0.2.1/32 dev dummy0
ip addr add 2001:db8::1/128 dev dummy0

# Create VM and add routed NIC.
lxc init "${IMAGE}" v1 --vm -s default -c limits.memory=512MiB
lxc config device add v1 eth0 nic \
    nictype=routed \
    parent=dummy0 \
    ipv4.address=192.0.2.2,192.0.2.3 \
    ipv6.address=2001:db8::2,2001:db8::3

NET_CONFIG_KEY="cloud-init.network-config"
if ! hasNeededAPIExtension cloud_init; then
    NET_CONFIG_KEY="user.network-config"
fi
lxc config set v1 "${NET_CONFIG_KEY}" - << EOF
network:
  version: 2
  ethernets:
    enp5s0:
      routes:
      - to: default
        via: 169.254.0.1
        on-link: true
      - to: default
        via: fe80::1
        on-link: true
      addresses:
      - 192.0.2.2/32
      - 192.0.2.3/32
      - 2001:db8::2/128
      - 2001:db8::3/128
EOF

lxc start v1

# Wait for VM to start.
waitInstanceReady v1
sleep 10

# Test ping to/from VM NIC.
ping -c1 -4 -W5 192.0.2.2
ping -c1 -6 -W5 2001:db8::2
lxc exec v1 -- ping -c1 -4 -W5 192.0.2.1
lxc exec v1 -- ping -c1 -6 -W5 2001:db8::2
lxc exec v1 -- ping -c1 -4 -W5 169.254.0.1
lxc exec v1 -- ping -c1 -6 -W5 -I enp5s0 fe80::1

# Cleanup.
lxc delete -f v1
ip link delete dummy0
lxc storage delete default

# shellcheck disable=SC2034
FAIL=0
