#!/bin/bash
set -eu

# Install LXD
install_lxd

# Test
set -x

export DEBIAN_FRONTEND=noninteractive
export HOME=/root

# Run the pylxd tests
[ -d pylxd ] || git clone --depth=1 https://github.com/canonical/pylxd
cd pylxd
integration/run-integration-tests

# shellcheck disable=SC2034
FAIL=0
