#!/bin/bash
set -eux

TEST_USER="testuser"

# Install lxd without starting daemon
install_lxd false

test_lxc() {
    DURATION="${1}"

    echo "Warmup"
    lxc help >/dev/null

    echo "Repeatedly call 'lxc help' for ${DURATION} and see how fast/slow it is"
    # shellcheck disable=SC2016
    ITERATIONS="$(timeout "${DURATION}" bash -c 'i=0; trap "echo \$i" EXIT; while i=$((i+1)); do lxc help >/dev/null; done' || true)"
    FORKS_PER_SECOND="$(awk "BEGIN {printf \"%d\n\", ${ITERATIONS}/${DURATION}}")"

    # Check that lxc forks/s are not below a certain threshold
    if [ "${FORKS_PER_SECOND}" -lt 15 ]; then
        echo "::warning::lxc forks/s: ${FORKS_PER_SECOND} (< 15/s)"
    else
        echo "::notice::lxc forks/s: ${FORKS_PER_SECOND}"
    fi
}

# Repeatedly call 'lxc help'
test_lxc 30

# Set preseed via snap
snap set lxd daemon.preseed='{"config": {"core.https_address": "[::]:8443"}}'

lxd waitready --timeout=300

# Check that preseed via snap works
[ "$(lxc config get core.https_address)" = "[::]:8443" ]

# Check that user access works
useradd -m ${TEST_USER} -G lxd
LXC=$(command -v lxc)
su ${TEST_USER} -c "${LXC} info"

# Cleanup
echo "==> Deleting test user"
userdel -r ${TEST_USER} 2>/dev/null || true

# shellcheck disable=SC2034
FAIL=0
