#!/bin/sh
set -eux

TEST_USER="testuser"

# Configure to use the proxy
curl -s http://canonical-lxd.stgraber.org/config/snapd.sh | sh

if [ "${track}" = "latest" ]; then
    snapd_channel=${channel}
else
    snapd_channel=${track}/${channel}
fi

echo "==> Installing LXD snap from ${track}/${channel}"
snap remove lxd || true
snap version
snap list
snap install lxd --channel="${snapd_channel}" --cohort=+

for _ in $(seq 60); do
    lxd waitready --timeout=10 >/dev/null 2>&1 && break
done

lxc --version

# LXD setup
lxc storage create default dir
lxc profile device add default root disk pool=default path=/

lxc network create lxdbr0
lxc profile device add default eth0 nic nictype=bridged parent=lxdbr0 name=eth0

systemctl restart snap.lxd.daemon.service

for _ in $(seq 60); do
    lxd waitready --timeout=10 >/dev/null 2>&1 && break
done

# Check that user access works
useradd -m ${TEST_USER} -G lxd
LXC=$(command -v lxc)
su ${TEST_USER} -c "${LXC} info"

# Cleanup
echo "==> Deleting test user"
userdel -r ${TEST_USER} 2>/dev/null || true

echo "==> Deleting network device"
lxc profile device remove default eth0

echo "==> Deleting network"
lxc network delete lxdbr0

echo "==> Deleting storage"
lxc profile device remove default root
lxc storage delete default

# shellcheck disable=SC2034
FAIL=0
