#!/bin/bash
set -eux

TEST_USER="testuser"

# Install lxd without starting daemon
install_lxd false

# Set preseed via snap
snap set lxd daemon.preseed='{"config": {"core.https_address": "[::]:8443"}}'

lxd waitready --timeout=300

# Check that preseed via snap works
[ "$(lxc config get core.https_address)" = "[::]:8443" ]

# Check that user access works
useradd -m ${TEST_USER} -G lxd
LXC=$(command -v lxc)
su ${TEST_USER} -c "${LXC} info"

# Cleanup
echo "==> Deleting test user"
userdel -r ${TEST_USER} 2>/dev/null || true

# shellcheck disable=SC2034
FAIL=0
