#!/bin/sh -eux
CNAME="docker-$(uuidgen)"

waitSnapdSeed() (
  set +x
  for i in $(seq 60); do # Wait up to 60s.
    if systemctl show snapd.seeded.service --value --property SubState | grep -qx exited; then
      return 0 # Success.
    fi

    sleep 1
  done

  echo "snapd not seeded after ${i}s"
  return 1 # Failed.
)

cleanup() {
    echo ""
    if [ "${FAIL}" = "1" ]; then
        echo "Test failed"
        exit 1
    fi

    echo "Test passed"
    exit 0
}

FAIL=1
trap cleanup EXIT HUP INT TERM

# Wait for snapd seeding
waitSnapdSeed

# Install LXD
while [ -e /usr/bin/lxd ]; do
    apt-get remove --purge --yes lxd lxd-client lxcfs liblxc1
done
apt-get remove --purge cloud-init --yes
snap remove lxd || true
snap install lxd --channel=latest/edge
apt-get install --no-install-recommends --yes jq
lxd waitready --timeout=300

lxd init --auto
set -x

# Create the container
lxc launch images:ubuntu/bionic "${CNAME}" -c security.nesting=true "$@"

(
cat << EOF
#!/bin/sh
# Wait for network
sleep 10
set -eux

# Install distro docker
apt-get update --yes --force-yes
apt-get install --no-install-recommends --yes --force-yes apparmor docker.io wget
systemctl start apparmor

# Stop the distro docker
systemctl stop docker.service
systemctl stop docker.socket

# Download binaries built from current git head of the Docker repo.
for BIN in docker dockerd docker-containerd docker-containerd-shim docker-init docker-proxy docker-runc; do
    wget -q "https://master.dockerproject.org/linux/x86_64/\${BIN}" -O "/usr/bin/\${BIN}" && \
        chmod +x "/usr/bin/\${BIN}"
done

# Start docker again
systemctl start docker
sleep 5

# Test whether we can pull a simple Docker image.
docker pull busybox:latest

# Test whether we can remove a simple Docker image.
docker rmi busybox:latest

# Show docker info (client and daemon version, etc.)
docker info

# Run a basic hello-world
docker run hello-world
EOF
) | lxc exec "${CNAME}" -- sh -eux

lxc delete --force "${CNAME}"
FAIL=0
