#!/bin/bash
set -eux

# Install LXD
install_lxd

# Configure LXD
lxd init --auto

IMAGE="${TEST_IMG:-ubuntu-minimal-daily:24.04}"

# Launch test instance
lxc launch "${IMAGE}" vm1 --vm
waitInstanceBooted vm1

echo "==> Test cleanly stopping a VM"
lxc stop vm1

# Cleanup
lxc delete -f vm1

# shellcheck disable=SC2034
FAIL=0
