#!/bin/bash
set -eux

# Install LXD
install_lxd

# Configure LXD
lxd init --auto

IMAGE="${TEST_IMG:-ubuntu-minimal-daily:24.04}"

# Launch test instance
lxc launch "${IMAGE}" vm1 --vm
waitInstanceBooted vm1

echo "==> Test cleanly stopping a VM"
lxc stop vm1

if ! echo "${LXD_SNAP_CHANNEL}" | grep -qE '^4\.0/'; then
    echo "==> Test lxc exec exit code upon VM disconnection due to a stop/reboot"
    lxc start vm1
    waitInstanceBooted vm1

    echo "==> Test lxc exec exit code when stopping the VM cleanly"
    (sleep 5 && lxc stop vm1) &
    lxc exec vm1 -- sleep 60 || exitCode=$?
    [ "${exitCode:-0}" -eq 129 ]
    wait $!

    echo "==> Test lxc exec exit code when stopping the VM abruptly"
    lxc start vm1
    waitInstanceBooted vm1
    (sleep 5 && lxc stop -f vm1) &
    lxc exec vm1 -- sleep 60 || exitCode=$?
    [ "${exitCode:-0}" -eq 129 ]
    wait $!
fi

# Cleanup
lxc delete -f vm1

# shellcheck disable=SC2034
FAIL=0
