name: Setup Environment
description: Composite action that sets up the environment for building and testing images

inputs:
  lxd-channel:
    description: LXD snap channel to install
    default: latest/edge
  go-version:
    description: Go version to install
    default: 1.22.x
  ssh-key:
    description: LXD imagebuilder deployment key
    required: true

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y --no-install-recommends \
            debootstrap \
            git \
            gpg \
            make
            qemu-utils \
            rsync \
            squashfs-tools

    - name: Install Go ${{ inputs.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: "${{ inputs.go-version }}"

    - name: Clone LXD imagebuilder
      shell: bash
      run: |
        git clone https://github.com/canonical/lxd-imagebuilder --depth 1

    - name: Build LXD imagebuilder
      shell: bash
      run: |
        cd lxd-imagebuilder
        make

    - name: Setup LXD ${{ inputs.lxd-channel }}
      shell: bash
      run: |
        sudo snap refresh lxd --channel=${{ inputs.lxd-channel }}
        sudo lxd waitready --timeout 60
        sudo chmod 777 /var/snap/lxd/common/lxd/unix.socket
        sudo lxd init --auto
        lxc version

    - name: Print supported LXD drivers
      shell: bash
      run: |
        lxc query /1.0 | jq '.environment.driver'
        sudo lxc query /1.0 | jq '.environment.driver'
