name: Setup Environment
description: Composite action that sets up the environment for building and testing images

inputs:
  lxd-channel:
    description: LXD snap channel to install
    default: latest/edge
  lxd-imagebuilder-channel:
    description: LXD imagebuilder snap channel to install
    default: latest/edge

runs:
  using: composite
  steps:
    - name: Check connectivity for SFTP upload
      shell: bash
      run: |
        set -eux

        # Try to get own public IP
        MY_PUBLIC_IP="$(curl --silent --max-time 5 https://api.ipify.org || true)"
        [ "${MY_PUBLIC_IP}" = "" ] && exit 0
        command -v nc || exit 0

        # Test connectivity to SFTP server
        SUCCESS="false"
        for attempt in 1 2 3 4 5; do
          echo "Try to connect from ${MY_PUBLIC_IP}..."
          if nc -w 5 -zv images.lxd.canonical.com 922; then
            SUCCESS="true"
            break
          fi
        done

        # Fail the job if the connection did not succeed.
        [ "${SUCCESS}" = "true" ]

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y --no-install-recommends \
            build-essential \
            bzip2 \
            debootstrap \
            btrfs-progs \
            dosfstools \
            gdisk \
            git \
            gpg \
            gpg-agent \
            jq \
            make \
            qemu-utils \
            rsync \
            squashfs-tools \
            umoci

    - name: Setup LXD Imagebuilder ${{ inputs.lxd-imagebuilder-channel }}
      env:
        SNAP_CHANNEL: ${{ inputs.lxd-imagebuilder-channel }}
      shell: bash
      run: |
        sudo snap install lxd-imagebuilder --channel="${SNAP_CHANNEL}" --classic
        lxd-imagebuilder --version

    - name: Setup LXD ${{ inputs.lxd-channel }}
      uses: canonical/setup-lxd@main
      with:
        channel: ${{ inputs.lxd-channel }}
