name: GPU passthrough

on:
  pull_request:
    paths:
      - '.github/workflows/gpu-passthrough-tests.yml'
      - '.github/workflows/testflinger/**'
  schedule:
    - cron: '38 6 */5 * *'
  workflow_dispatch:
    inputs:
      ubuntu-releases:
        description: Ubuntu releases to run the tests against. In JSON format, i.e. '["jammy", "noble"]'.
        type: choice
        default: '["noble"]'
        options:
          - '["jammy", "noble"]'
          - '["jammy"]'
          - '["noble"]'
      snap-track:
        description: Snap track to run the tests i.e. '["latest/edge", "6/candidate"]'.
        type: choice
        default: '["latest/edge"]'
        options:
          - '["latest/edge"]'
          - '["latest/candidate"]'
          - '["latest/stable"]'
          - '["6/edge"]'
          - '["6/candidate"]'
          - '["6/stable"]'
          - '["5.21/edge"]'
          - '["5.21/candidate"]'
          - '["5.21/stable"]'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ inputs.ubuntu-releases }}-${{ inputs.snap-track }}
  # XXX: scheduled runs should not cancel manually triggered ones
  cancel-in-progress: ${{ !contains(github.event_name, 'schedule')}}

env:
  TESTFLINGER_DIR: .github/workflows/testflinger

jobs:
  # uc-nvidia-cdi:
  #   runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
  #   strategy:
  #     matrix:
  #       track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
  #       os:
  #         - core24-latest
  #   env:
  #     SNAP_CHANNEL: ${{ matrix.track }}
  #     TFWORKFLOW: uc-nvidia-cdi-job
  #   steps:
  #     - name: Event data
  #       run: "echo ::notice::Snap channel: $SNAP_CHANNEL"
  #
  #     - name: Checkout code
  #       uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
  #       with:
  #         persist-credentials: false
  #
  #     - name: Create Testflinger job
  #       env:
  #         JOB_QUEUE: lxd-nvidia
  #         DISTRO: ${{ matrix.os }}
  #       working-directory: ${{ env.TESTFLINGER_DIR }}
  #       run: ./run.sh --dryrun
  #
  #     - name: Run tests
  #       uses: canonical/testflinger/.github/actions/submit@eacde25fc895399c96961496096e4cb7d1b38a37 # main
  #       with:
  #         poll: true
  #         job-path: ${{ env.TESTFLINGER_DIR }}/${{ env.TFWORKFLOW }}.yml.tmp

  # nvidia-cdi:
  #   runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
  #   strategy:
  #     matrix:
  #       track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
  #       os: ${{ fromJSON(inputs.ubuntu-releases || '["noble"]') }}
  #   env:
  #     SNAP_CHANNEL: ${{ matrix.track }}
  #     TFWORKFLOW: nvidia-cdi-job
  #   steps:
  #     - name: Event data
  #       run: "echo ::notice::Snap channel: $SNAP_CHANNEL"
  #
  #     - name: Checkout code
  #       uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
  #       with:
  #         persist-credentials: false
  #
  #     - name: Create Testflinger job
  #       env:
  #         JOB_QUEUE: lxd-nvidia
  #         DISTRO: ${{ matrix.os }}
  #       working-directory: ${{ env.TESTFLINGER_DIR }}
  #       run: ./run.sh --dryrun
  #
  #     - name: Run tests
  #       uses: canonical/testflinger/.github/actions/submit@eacde25fc895399c96961496096e4cb7d1b38a37 # main
  #       with:
  #         poll: true
  #         job-path: ${{ env.TESTFLINGER_DIR }}/${{ env.TFWORKFLOW }}.yml.tmp

  # nvidia-legacy-runtime:
  #   runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
  #   strategy:
  #     matrix:
  #       track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
  #       os: ${{ fromJSON(inputs.ubuntu-releases || '["noble"]') }}
  #   env:
  #     SNAP_CHANNEL: ${{ matrix.track }}
  #     TFWORKFLOW: nvidia-legacy-runtime-job
  #   steps:
  #     - name: Event data
  #       run: "echo ::notice::Snap channel: $SNAP_CHANNEL"
  #
  #     - name: Checkout code
  #       uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
  #       with:
  #         persist-credentials: false
  #
  #     - name: Create Testflinger job
  #       env:
  #         JOB_QUEUE: lxd-nvidia
  #         DISTRO: ${{ matrix.os }}
  #       working-directory: ${{ env.TESTFLINGER_DIR }}
  #       run: ./run.sh --dryrun
  #
  #     - name: Run tests
  #       uses: canonical/testflinger/.github/actions/submit@eacde25fc895399c96961496096e4cb7d1b38a37 # main
  #       with:
  #         poll: true
  #         job-path: ${{ env.TESTFLINGER_DIR }}/${{ env.TFWORKFLOW }}.yml.tmp

  nvidia-mig:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    strategy:
      matrix:
        track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
        os: ${{ fromJSON(inputs.ubuntu-releases || '["noble"]') }}
    env:
      SNAP_CHANNEL: ${{ matrix.track }}
      TFWORKFLOW: nvidia-mig-job
    steps:
      - name: Event data
        run: "echo ::notice::Snap channel: $SNAP_CHANNEL"

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Create Testflinger job
        env:
          JOB_QUEUE: torchtusk
          DISTRO: ${{ matrix.os }}
        working-directory: ${{ env.TESTFLINGER_DIR }}
        run: ./run.sh --dryrun

      - name: Run tests
        uses: canonical/testflinger/.github/actions/submit@eacde25fc895399c96961496096e4cb7d1b38a37 # main
        with:
          poll: true
          job-path: ${{ env.TESTFLINGER_DIR }}/${{ env.TFWORKFLOW }}.yml.tmp

  # amd-cdi:
  #   runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
  #   strategy:
  #     matrix:
  #       track: ${{ fromJSON(inputs.snap-track || '["latest/edge"]') }}
  #       os: ${{ fromJSON(inputs.ubuntu-releases || '["noble"]') }}
  #   env:
  #     SNAP_CHANNEL: ${{ matrix.track }}
  #     TFWORKFLOW: amd-cdi-job
  #   steps:
  #     - name: Event data
  #       run: "echo ::notice::Snap channel: $SNAP_CHANNEL"
  #
  #     - name: Checkout code
  #       uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
  #       with:
  #         persist-credentials: false
  #
  #     - name: Create Testflinger job
  #       env:
  #         JOB_QUEUE: lxd-amd
  #         DISTRO: ${{ matrix.os }}
  #       working-directory: ${{ env.TESTFLINGER_DIR }}
  #       run: ./run.sh --dryrun
  #
  #     - name: Run tests
  #       uses: canonical/testflinger/.github/actions/submit@eacde25fc895399c96961496096e4cb7d1b38a37 # main
  #       with:
  #         poll: true
  #         job-path: ${{ env.TESTFLINGER_DIR }}/${{ env.TFWORKFLOW }}.yml.tmp
