name: Tests (snap)
on:
  - workflow_dispatch

permissions:
  contents: read

jobs:
  network-routed:
    name: Network Routed
    runs-on: [self-hosted, linux, X64, jammy, large]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test script
        run: |
          sudo tests/network-routed
